apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: go-hpa
spec: #spec do deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: go-hpa
    spec:
      containers:
      - name: golang
        image: thiagogmc/go-hpa
        ports:
        - containerPort: 80

        resources:
          requests:
            # memory: "64Mi"
            cpu: "50m"
          limits:
            cpu: "100m"